name = "stardos"
version = "0.0.0-development"
gleam = ">= 1.13.0"

description = "An integrated, concurrent, cross-runtime library for OS resources in Gleam!"
repository = { type = "github", user = "acandoo", repo = "stardos" }
licences = ["MIT"]

target = "javascript"

[documentation]
pages = [
  { title = "Contributing", path = "contributing.html", source = "./docs/CONTRIBUTING.md" },
  { title = "Design rationale", path = "rationale.html", source = "./docs/RATIONALE.md" },
  { title = "Concurrency", path = "concurrency.html", source = "./docs/CONCURRENCY.md" }
]

[dependencies]
gleam_stdlib = ">= 0.67.1 and < 1.0.0"
gleam_time = ">= 1.7.0 and < 2.0.0"
gleither = ">= 2.2.1 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
shellout = ">= 1.7.0 and < 2.0.0"
antimonia = ">= 1.1.0 and < 2.0.0"

[javascript]
typescript_declarations = true

[javascript.deno]
allow_env = true
allow_read = true
allow_run = true
